# Generated by Django 3.2.11 on 2022-04-21 18:46

from django.db import migrations
import django_resized.forms
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=70, size=[1200, 630], upload_to=photos.models.get_photos_filename),
        ),
    ]
