# Generated by Django 3.2.11 on 2022-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
