# Generated by Django 3.2.11 on 2022-11-09 10:22

from django.db import migrations
import django_resized.forms
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_album_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, size=[1200, 630], upload_to=photos.models.get_photos_filename),
        ),
    ]
