# Generated by Django 3.2.11 on 2022-12-13 14:18

from django.db import migrations
import django_resized.forms
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[1920, 1080], upload_to=photos.models.get_photos_filename),
        ),
    ]
