# Generated by Django 3.2.11 on 2024-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipprice',
            name='type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
