# Generated by Django 3.2.11 on 2024-01-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_membershipprice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipprice',
            name='type',
        ),
        migrations.AlterField(
            model_name='membershipprice',
            name='price_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
