# Generated by Django 3.2.11 on 2024-02-15 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20240124_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipprice',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
    ]
