# Generated by Django 3.2.10 on 2021-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('max_attendees', models.IntegerField(null=True)),
            ],
        ),
    ]
