# Generated by Django 3.2.11 on 2022-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_popup',
            field=models.BooleanField(default=False),
        ),
    ]
