# Generated by Django 3.2.11 on 2022-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_max_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SD', 'Summer Day Walk'), ('SW', 'Summer Weekend'), ('WD', 'Winter Day Walk'), ('WW', 'Winter Weekend'), ('CL', 'Climbing'), ('SO', 'Social'), ('XX', 'Other')], default='XX', max_length=2),
        ),
    ]
