# Generated by Django 3.2.11 on 2022-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendinguser',
            name='is_driving',
            field=models.BooleanField(default=False),
        ),
    ]
