# Generated by Django 3.2.11 on 2023-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_open',
            field=models.BooleanField(default=True),
        ),
    ]
