# Generated by Django 3.2.11 on 2023-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendinguser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
