# Generated by Django 3.2.11 on 2023-05-08 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_attendinguser_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendinguser',
            name='list_join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
