# Generated by Django 3.2.11 on 2023-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_attendinguser_list_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendinguser',
            old_name='is_driving',
            new_name='is_trip_paid',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SD', 'Summer Day Walk'), ('SW', 'Summer Weekend'), ('WD', 'Winter Day Walk'), ('WW', 'Winter Weekend'), ('CL', 'Climbing'), ('SO', 'Social'), ('CM', 'Committee'), ('XX', 'Other')], default='XX', max_length=2),
        ),
    ]
