# Generated by Django 3.2.11 on 2024-01-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_signup_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
