# Generated by Django 3.2.11 on 2023-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_signup_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signup_open_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
