# Generated by Django 3.2.11 on 2024-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
