# Generated by Django 3.2.11 on 2024-01-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
