# Generated by Django 3.2.11 on 2024-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kit", "0002_alter_kit_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
