# Generated by Django 3.2.11 on 2024-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_auto_20240824_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitborrow',
            name='collection_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='kitborrow',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
