# Generated by Django 3.2.11 on 2024-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_alter_kit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='text_id',
            field=models.CharField(default='nothing', max_length=50),
            preserve_default=False,
        ),
    ]
