# Generated by Django 3.2.11 on 2024-08-25 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_auto_20240825_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitborrow',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
