# Generated by Django 3.2.10 on 2021-12-15 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, verbose_name='about you'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hillwalking', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('scrambling', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('trad_climbing', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('winter_walking', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('winter_climbing', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('ski_touring', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('trail_running', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('indoor_climbing', models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Beginner'), (2, 'Competent'), (3, 'Happy Leading')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
