# Generated by Django 3.2.11 on 2022-03-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_case_emergency',
            field=models.TextField(blank=True, verbose_name='emergency'),
        ),
    ]
