# Generated by Django 3.2.11 on 2022-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='committee_bio',
            field=models.TextField(blank=True, verbose_name='commitee bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='committee_role',
            field=models.TextField(blank=True, choices=[('Chair', 'Chair'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('General', 'General'), (None, 'No role')], verbose_name='committee role'),
        ),
    ]
