# Generated by Django 3.2.10 on 2022-01-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_experience_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='experience', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
