# Generated by Django 3.2.10 on 2022-01-05 17:32

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20220105_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.get_profile_pic_filename),
        ),
        migrations.AlterField(
            model_name='experience',
            name='hillwalking',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='indoor_climbing',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='scrambling',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ski_touring',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='trad_climbing',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='trail_running',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='winter_climbing',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='winter_walking',
            field=models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Second'), (3, 'Leader')]),
        ),
    ]
