# Generated by Django 3.2.11 on 2022-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20220428_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_discord',
            field=models.BooleanField(default=False),
        ),
    ]
