# Generated by Django 3.2.11 on 2023-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_user_is_on_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_walk_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
