# Generated by Django 3.2.11 on 2023-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_user_is_walk_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='committee_role',
            field=models.TextField(blank=True, choices=[('Chair', 'Chair'), ('Vice-Chair', 'Vice-Chair'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('General', 'General'), (None, 'No role')], verbose_name='committee role'),
        ),
    ]
