# Generated by Django 3.2.10 on 2022-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_committee',
            field=models.BooleanField(default=False),
        ),
    ]
