# Generated by Django 3.2.11 on 2024-01-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_user_committee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_winter_skills',
            field=models.BooleanField(default=False),
        ),
    ]
