# Generated by Django 3.2.10 on 2022-01-11 13:59

from django.db import migrations
import django_resized.forms
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_user_is_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, size=[320, 320], upload_to=members.models.get_profile_pic_filename),
        ),
    ]
