# Generated by Django 3.2.11 on 2024-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_user_is_winter_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
