# Generated by Django 3.2.10 on 2022-01-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
