# Generated by Django 3.2.10 on 2022-01-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='experience', serialize=False, to='members.user')),
                ('activity', models.TextField(choices=[('HW', 'Hillwalking'), ('WW', 'Winter Walking'), ('SC', 'Scrambling'), ('IC', 'Indoor Climbing'), ('IB', 'Indoor Bouldering'), ('OS', 'Sport Climbing'), ('OT', 'Trad Climbing'), ('WC', 'Winter Climbing'), ('ST', 'Ski Touring')])),
                ('competency', models.IntegerField(choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Competent'), (3, 'Experienced')])),
            ],
        ),
    ]
