# Generated by Django 3.2.11 on 2024-01-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_user_discord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_username',
        ),
    ]
