# Generated by Django 3.2.11 on 2024-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_user_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
