# Generated by Django 3.2.10 on 2022-01-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20220112_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'activity')},
        ),
    ]
