# Generated by Django 3.2.11 on 2024-02-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_user_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_username',
        ),
    ]
