# Generated by Django 3.2.10 on 2022-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_experience_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='competency',
            field=models.IntegerField(blank=True, choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Competent'), (3, 'Experienced')], null=True),
        ),
    ]
