# Generated by Django 3.2.10 on 2022-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_experience_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='competency',
            field=models.IntegerField(blank=True, choices=[(0, 'No Experience'), (1, 'Beginner'), (2, 'Competent'), (3, 'Experienced')], default=0),
        ),
    ]
