# Generated by Django 3.2.11 on 2024-02-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_user_discord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
