# Generated by Django 3.2.11 on 2024-02-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_user_membership_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_paid',
        ),
    ]
