# Generated by Django 3.2.11 on 2024-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_user_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dormant',
            field=models.BooleanField(default=False),
        ),
    ]
