# Generated by Django 3.2.11 on 2024-01-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='EventPost',
        ),
        migrations.DeleteModel(
            name='FeedPost',
        ),
    ]
