# Generated by Django 3.2.10 on 2022-01-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20220105_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
